update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,35 +37,30 @@ jobs:
   push-frontend:
     machine: true
     steps:
-      - checkout
-      - run: 
-          name : login
-          command: |
-            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
       - run:
-          name: docker image build
-          command: |
-            cd php-redis
-            ./run_docker.sh
-
+          command:
+            echo "pass"
+      # - checkout
+      # - run: 
+      #     name : login
+      #     command: |
+      #       echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
       # - run:
-      #     name: docker image upload
+      #     name: docker image build
       #     command: |
       #       cd php-redis
-      #       pwd
-      #       ls -al
-      #       ./upload_docker.sh
-      - run:
-          name: success
-          when: on_success
-          command: |
-            echo 'image upload success'
-      - run:
-          name: fail
-          when: on_fail
-          command: |
-            echo 'image upload fail'
-            exit 1;
+      #       ./run_docker.sh
+      # - run:
+      #     name: success
+      #     when: on_success
+      #     command: |
+      #       echo 'image upload success'
+      # - run:
+      #     name: fail
+      #     when: on_fail
+      #     command: |
+      #       echo 'image upload fail'
+      #       exit 1;
 
   setup-eks:
     docker:
@@ -76,6 +71,9 @@ jobs:
           name: install dependencies
           command: |
             yum -y install tar gzip
+      - run:
+          name: install eksctl
+          command: |
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp  
             mv /tmp/eksctl /usr/local/bin
       - run:
